-- CN02:
GRANT SELECT, UPDATE, INSERT ON CN02.CUSTOMER_INFO TO ROLE_MANAGER;
GRANT SELECT, INSERT, UPDATE ON CN02.INVOICELINE TO Manager;
GRANT SELECT ON CN02.BRANCH TO ROLE_MANAGER;
GRANT SELECT, INSERT, UPDATE ON CN02.MENU TO ROLE_MANAGER;


-- CN01:
GRANT SELECT, UPDATE, INSERT ON CN01.CUSTOMER_INFO TO ROLE_MANAGER;
GRANT SELECT ON CN01.INVOICE TO ROLE_MANAGER;
GRANT SELECT ON CN01.BRANCH TO ROLE_MANAGER;
GRANT SELECT, INSERT, UPDATE ON CN01.MENU TO ROLE_MANAGER;

CREATE DATABASE LINK DBL_CN01 CONNECT TO Manager IDENTIFIED BY GUEST USING 'CN01_LINK'
CONNECT Manager/manager;

-- Cài đặt câu lệnh xem mức cô lập:
Declare
trans_id Varchar2(100);
begin
trans_id := dbms_transaction.local_transaction_id( TRUE );
end;

-- Xem mức cô lập:
SELECT s.sid, s.serial#,
CASE BITAND(t.flag, POWER(2, 28))
WHEN 0 THEN 'READ COMMITTED'
ELSE 'SERIALIZABLE'
END AS isolation_level
FROM v$transaction t 
JOIN v$session s ON t.addr = s.taddr AND s.sid = sys_context('USERENV', 'SID');

-- ///// LOST UPDATED
-- ///// LOST UPDATED
-- ///// LOST UPDATED
-- CN02: 
SELECT * FROM CN02.CUSTOMER_INFO WHERE CustomerAddress = 'Ho Chi Minh';
-- CN01: 
SELECT * FROM CN02.CUSTOMER_INF0@DBL_CN01 WHERE CustomerAddress = 'Ho Chi Minh';
-- CN02: 
UPDATE CN02.CUSTOMER_INFO SET CustomerAddress = 'Da Lat' WHERE CustomerAddress = 'Ho Chi Minh';
-- CN01:
UPDATE CN02.CUSTOMER_INFO@DBL_CN01 SET CustomerAddress = 'Ha Noi' WHERE CustomerID = 'CUS01';
COMMIT;
-- CN02:
COMMIT;
SELECT * FROM CN02.CUSTOMER_INFO WHERE CustomerID = 'CUS01';

-- /// GIẢI PHÁP
-- /// GIẢI PHÁP
-- CN02:
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
SELECT * FROM CN02.CUSTOMER_INFO WHERE CustomerAddress = 'Binh Duong';
UPDATE CN02.CUSTOMER_INFO SET CustomerAddress = 'Thu Duc' WHERE CustomerAddress = 'Binh Duong';
-- CN01:
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE; 
UPDATE CN02.CUSTOMER_INFO@DBL_CN01 SET CustomerAddress = 'Vinh Phuc' WHERE CustomerID = 'CUS40';
COMMIT;
-- CN02:
COMMIT;
SELECT * FROM CN02.CUSTOMER_INFO WHERE CustomerID = 'CUS40';

-- ///// UNREPEATABLE READ 
-- ///// UNREPEATABLE READ 
-- ///// UNREPEATABLE READ 
-- CN02: SELECT * FROM CN02.CUSTOMER_INFO WHERE CustomerID = 'CUS11';
BEGIN
    printCustomerInfo('CUS11');
END; 
-- CN01: 
UPDATE CN02.CUSTOMER_INFO@DBL_CN01 SET PhoneNumber = '0366000000' WHERE CustomerID = 'CUS11';
COMMIT;
-- CN02: SELECT * FROM CN02.CUSTOMER_INFO WHERE CustomerID = 'CUS11';
BEGIN
    printCustomerInfo('CUS11');
END;
-- /// GIẢI PHÁP
-- /// GIẢI PHÁP
-- CN02: SELECT * FROM CN02.CUSTOMER_INFO WHERE CustomerID = 'CUS04';
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
BEGIN
    printCustomerInfo('CUS04');
END;
-- CN01:
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
UPDATE CN02.CUSTOMER_INFO@DBL_CN01 SET PhoneNumber = '0768888888' WHERE CustomerID = 'CUS04';
COMMIT;
-- CN02: SELECT * FROM CN02.CUSTOMER_INFO WHERE CustomerID = 'CUS04';
BEGIN
    printCustomerInfo('CUS04');
END;
COMMIT;
BEGIN
    printCustomerInfo('CUS04');
END;
-- ///// PHANTOM READ
-- ///// PHANTOM READ
-- ///// PHANTOM READ
-- CN02:
SELECT * FROM CN02.MENU WHERE MenuType = 'Banh Ngot';
-- CN01:
INSERT INTO CN02.MENU@DBL_CN01 VALUES ('ME51','Red Velvet','Banh Ngot',35000);
INSERT INTO CN02.MENU@DBL_CN01 VALUES ('ME52','Macarons','Banh Ngot',30000);
INSERT INTO CN02.MENU@DBL_CN01 VALUES ('ME53','Croissant','Banh Ngot',35000);
INSERT INTO CN02.MENU@DBL_CN01 VALUES ('ME54','Crepe','Banh Ngot',50000);
INSERT INTO CN02.MENU@DBL_CN01 VALUES ('ME55','Mille-fueille','Banh Ngot',35000);
INSERT INTO CN02.MENU@DBL_CN01 VALUES ('ME56','Banh Mi Baguette','Banh Ngot',25000);
COMMIT;
-- CN02
SELECT * FROM CN02.MENU WHERE MenuType = 'Banh Ngot';
COMMIT;

-- /// GIẢI PHÁP
-- /// GIẢI PHÁP
-- CN02:
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
SELECT * FROM CN02.MENU WHERE MenuType = 'Banh Ngot';
-- CN01
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
INSERT INTO CN02.MENU@DBL_CN01 VALUES ('ME57','Mochi','Banh Ngot',50000);
INSERT INTO CN02.MENU@DBL_CN01 VALUES ('ME58','Banh Ran Dorayaki','Banh Ngot',35000);
INSERT INTO CN02.MENU@DBL_CN01 VALUES ('ME59','Black Forest','Banh Ngot',35000);
INSERT INTO CN02.MENU@DBL_CN01 VALUES ('ME60','Madeleines','Banh Ngot',70000);
INSERT INTO CN02.MENU@DBL_CN01 VALUES ('ME61','Lamington','Banh Ngot',35000);
INSERT INTO CN02.MENU@DBL_CN01 VALUES ('ME62','Pandan','Banh Ngot',25000);
INSERT INTO CN02.MENU@DBL_CN01 VALUES ('ME63','Tapioca','Banh Ngot',40000);
COMMIT;
-- CN02
SELECT * FROM CN02.MENU WHERE MenuType = 'Banh Ngot';
COMMIT;
SELECT * FROM CN02.MENU WHERE MenuType = 'Banh Ngot';

-- ///// DEADLOCK
-- ///// DEADLOCK
-- ///// DEADLOCK
-- CN02:
UPDATE CN02.MENU SET SalePrice = 45000 WHERE MenuType = 'Tra Sua';
-- CN01:
UPDATE CN02.MENU@DBL_CN01 SET SalePrice = 30000 WHERE MenuType = 'Banh Ngot';
-- CN02:
UPDATE CN02.MENU SET SalePrice = 35000 WHERE MenuType = 'Banh Ngot';
-- CN01:
UPDATE CN02.MENU@DBL_CN01 SET SalePrice = 40000 WHERE MenuType = 'Tra Sua';

COMMIT;
-- CN02:
SELECT * FROM CN02.MENU WHERE MenuType = 'Banh Ngot';
SELECT * FROM CN02.MENU WHERE MenuType = 'Tra Sua';
-- /// GIẢI PHÁP
-- /// GIẢI PHÁP
-- CN02:
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
UPDATE CN02.MENU SET SalePrice = 70000 WHERE MenuType = 'Ca Phe Italy';
-- CN01:
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
UPDATE CN02.MENU@DBL_CN01 SET SalePrice = 45000 WHERE MenuType = 'Tra';
-- CN02:
UPDATE CN02.MENU SET SalePrice = 40000 WHERE MenuType = 'Tra';
-- CN01:
UPDATE CN02.MENU@DBL_CN01 SET SalePrice = 65000 WHERE MenuType = 'Ca Phe Italy';
COMMIT;
-- CN02:
SELECT * FROM CN02.MENU WHERE MenuType = 'Ca Phe Italy';
SELECT * FROM CN02.MENU WHERE MenuType = 'Tra';


