-- Chi nhanh 1
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

CREATE USER CN1 IDENTIFIED BY cn1;
CREATE USER CN2 IDENTIFIED BY cn2;
GRANT CONNECT, DBA TO CN1;
GRANT CONNECT TO CN2;

CREATE USER DIRECTOR IDENTIFIED BY director;
GRANT CONNECT TO DIRECTOR;
GRANT SELECT ON CN1.MENU TO DIRECTOR;
GRANT SELECT ON CN1.EMPLOYEE TO DIRECTOR;
GRANT SELECT ON CN1.BRANCH TO DIRECTOR;
GRANT SELECT ON CN1.INVOICE TO DIRECTOR;
GRANT SELECT ON CN1.INVOICELINE TO DIRECTOR;
GRANT SELECT ON CN1.CUSTOMER_INFO TO DIRECTOR;
GRANT SELECT ON CN1.CUSTOMER_MANAGER TO DIRECTOR;
GRANT SELECT ON CN1.MANAGEMENU_MANAGER TO DIRECTOR;
GRANT SELECT ON CN1.MANAGEMENU_STAFF TO DIRECTOR;
GRANT SELECT ON CN2.MENU TO DIRECTOR;
GRANT SELECT ON CN2.EMPLOYEE TO DIRECTOR;
GRANT SELECT ON CN2.BRANCH TO DIRECTOR;
GRANT SELECT ON CN2.INVOICE TO DIRECTOR;
GRANT SELECT ON CN2.INVOICELINE TO DIRECTOR;
GRANT SELECT ON CN2.CUSTOMER_INFO TO DIRECTOR;
GRANT SELECT ON CN2.CUSTOMER_MANAGER TO DIRECTOR;
GRANT SELECT ON CN2.MANAGEMENU_MANAGER TO DIRECTOR;
GRANT SELECT ON CN2.MANAGEMENU_STAFF TO DIRECTOR;

CREATE USER MANAGER IDENTIFIED BY manager;
GRANT SELECT, UPDATE, INSERT ON CN1.MENU TO MANAGER;
GRANT SELECT, UPDATE, DELETE, INSERT ON CN1.EMPLOYEE TO MANAGER;
GRANT SELECT ON CN1.BRANCH TO MANAGER;
GRANT SELECT ON CN1.INVOICE TO MANAGER;
GRANT SELECT ON CN1.INVOICELINE TO MANAGER;
GRANT SELECT ON CN1.CUSTOMER_INFO TO MANAGER;
GRANT SELECT, INSERT, UPDATE ON CN1.CUSTOMER_MANAGER TO MANAGER;
GRANT SELECT, INSERT, UPDATE ON CN1.MANAGEMENU_MANAGER TO MANAGER;
GRANT SELECT ON CN1.MANAGEMENU_STAFF TO MANAGER;

CREATE USER STAFF IDENTIFIED BY staff;
GRANT SELECT ON CN1.MENU TO MANAGER;
GRANT SELECT, INSERT, UPDATE ON CN1.INVOICE TO MANAGER;
GRANT SELECT, INSERT, UPDATE ON CN1.INVOICELINE TO MANAGER;
GRANT SELECT, INSERT, UPDATE ON CN1.CUSTOMER_INFO TO MANAGER;
GRANT SELECT, UPDATE ON CN1.MANAGEMENU_STAFF TO MANAGER;

-- Chi nhanh 2
CREATE USER CN1 IDENTIFIED BY cn1;
CREATE USER CN2 IDENTIFIED BY cn2;
GRANT CONNECT, DBA TO CN2;
GRANT CONNECT TO CN1;

...